### PR TITLE
Julia 0.7/1.0/1.1 support

### LINKED ISSUE #22: BloomFilters does not work on Julia v1.0
```julia
v1.0) pkg> activate .

(Test) pkg> add https://github.com/johnmyleswhite/BloomFilters.jl
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/johnmyleswhite/BloomFilters.jl`
 Resolving package versions...
  Updating `Project.toml`
  [d3d7f49f] + BloomFilters v0.2.0+ #master (https://github.com/johnmyleswhite/BloomFilters.jl)
  Updating `Manifest.toml`
  [d3d7f49f] + BloomFilters v0.2.0+ #master (https://github.com/johnmyleswhite/BloomFilters.jl)
  [34da2185] + Compat v1.1.0
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 

julia> using BloomFilters
[ Info: Precompiling BloomFilters [d3d7f49f-8593-5289-ba71-9c4f4848f489]
ERROR: LoadError: LoadError: UndefVarError: contains not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /home/ajaym/.julia/packages/BloomFilters/6zNxm/src/BloomFilters.jl:1
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/ajaym/.julia/packages/BloomFilters/6zNxm/src/bloom-filter.jl:122
in expression starting at /home/ajaym/.julia/packages/BloomFilters/6zNxm/src/BloomFilters.jl:3
ERROR: Failed to precompile BloomFilters [d3d7f49f-8593-5289-ba71-9c4f4848f489] to /home/ajaym/.julia/compiled/v1.0/BloomFilters/ddTJ4.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
```

### PR DESCRIPTION
**Pull request by scls19fr**
Julia 0.7/1.0/1.1 support

Using [Test](https://docs.julialang.org/en/v1/stdlib/Test/) from stdlib
 - Uses `@testset` macro
 - changes `@assert` to `@test`

Using `in` instead of `contains`

Deprecates `contains`

Using parametric type instead of `Any`

Minor fixes to `README.md` documentation

Closes #22

Replaces #20 #23

### CODE REVIEW

File: src/bloom-filter.jl [hunk 1]
```diff
@@ -129,20 +129,20 @@ function Base.contains(bf::BloomFilter, key::Any)
     return true
 end
 
-Base.in(key::Any, bf::BloomFilter) = contains(bf, key)
+# @deprecate contains(bf::BloomFilter, key::T) where {T} in(key, bf)
```
Comment (scls19fr) [inline src/bloom-filter.jl]: I don't know why I can't do this.
Any idea?

**Comment by scls19fr** [comment]
@johnmyleswhite and/or @boydgreenfield could you review?

**Comment by boydgreenfield** [comment]
@scls19fr This looks great, thanks for the PR! (And especially a solution that supports 0.7 and 1.0/1.1)

I need to update my Julia install 😬, but will try to do that tomorrow or Tuesday and get an updated package released. Thanks again!

**Comment by schlurp** [comment]
Hi, how is the status of the package update? On julia 1.1 I cannot install the bloom filters package out of the box.

**Comment by boydgreenfield** [comment]
@schlurp Merged now. Thanks for the ping and reminder (I somehow missed the reminder on this I set for myself, sorry about that!)

**Comment by boydgreenfield** [comment]
@schlurp @scls19fr This is... embarrassing, but I've just spent the last 15 minutes trying to figure out how to update the package in the registry now. Do either of you know what the latest guidance is?

I was trying to do it with `Pkg` (which I remember from 0.6.0), then found broken links to attobot, then the `pkg` sub-command, then `PkgDev`... etc. 🙍‍♂

**Comment by scls19fr** [comment]
I think you need to use now https://github.com/JuliaRegistries/Registrator.jl 
See https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677?page=8

**Comment by scls19fr** [comment]
I think that switching from `REQUIRE` to `project.toml` is required now.
[`gen_project.jl`](https://github.com/JuliaLang/Pkg.jl/blob/master/bin/gen_project.jl) can help
